[build]
builder = "nixpacks"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "sh -c 'bash bin/start.sh'"
restartPolicyMaxRetries = 5
healthcheckPath = "/"
healthcheckTimeout = 30
healthcheckInterval = 10
